"""Composable positional encoding channels for MLPRope experiments."""

from position.autograd import exp_with_identity_grad
from position.basis import (
    FrozenFourierBasis,
    build_position_basis,
    interleaved_fourier_basis,
)
from position.channels import (
    AttentionPositionWriteChannel,
    PositionChannel,
    QKPositionChannel,
    QKPositionOutput,
    ResidualPositionChannel,
    adapt_legacy_position_state_dict,
    build_attention_position_write_channel,
    build_qk_position_channel,
    build_residual_position_channel,
    count_position_parameters,
    load_position_compatible_state_dict,
)
from position.clock import (
    ROTARY_CLOCK_DEFAULTS,
    RotaryClockController,
    RotaryClockState,
    normalize_rotary_clock_config,
)
from position.config import (
    POSITION_PRESETS,
    POSITION_SCHEMA_VERSION,
    POSITION_VARIANTS,
    V1_CHANNEL_DEFAULTS,
    V2_CHANNEL_DEFAULTS,
    ATTENTION_WRITE_DEFAULTS,
    RESIDUAL_STREAM_DEFAULTS,
    channel_theta,
    deep_merge,
    ensure_channel_v2,
    legacy_position_run_tag,
    normalize_logit_bias_config,
    normalize_position_config_v2,
    normalize_position_content_config,
    normalize_attention_write_config,
    normalize_residual_stream_config,
    resolve_channel_config,
    upgrade_legacy_position_config,
    v2_position_run_tag,
)
from position.frequency import (
    ROPE_FREQUENCY_DEFAULTS,
    ROPE_FREQUENCY_MAPPERS,
    ROPE_FREQUENCY_PARAMETERIZATIONS,
    RopeFrequencyController,
    legacy_rope_frequency_mode,
    normalize_rope_frequency_config,
    parameterize_rope_frequencies,
)
from position.gain import (
    POSITION_GAIN_DEFAULTS,
    PositionGain,
    PositionGainOutput,
    normalize_position_gain_config,
)
from position.mappers import FeatureMapper, build_mapper
from position.preprojection import (
    QK_PREPROJECTION_DEFAULTS,
    QKPreprojectionPosition,
    normalize_qk_preprojection_config,
)
from position.temporal import CausalControlMapper, CausalEMA, CausalEMAState
from position.rotary import (
    apply_rotary,
    build_rope_cache,
    build_rope_frequencies,
    compose_phase,
    rotate_half,
)

__all__ = [
    "FrozenFourierBasis",
    "FeatureMapper",
    "AttentionPositionWriteChannel",
    "ResidualPositionChannel",
    "POSITION_PRESETS",
    "POSITION_SCHEMA_VERSION",
    "POSITION_VARIANTS",
    "PositionChannel",
    "QKPositionChannel",
    "QKPositionOutput",
    "V1_CHANNEL_DEFAULTS",
    "V2_CHANNEL_DEFAULTS",
    "ATTENTION_WRITE_DEFAULTS",
    "RESIDUAL_STREAM_DEFAULTS",
    "ROPE_FREQUENCY_DEFAULTS",
    "ROPE_FREQUENCY_MAPPERS",
    "ROPE_FREQUENCY_PARAMETERIZATIONS",
    "ROTARY_CLOCK_DEFAULTS",
    "POSITION_GAIN_DEFAULTS",
    "QK_PREPROJECTION_DEFAULTS",
    "RopeFrequencyController",
    "RotaryClockController",
    "RotaryClockState",
    "PositionGain",
    "PositionGainOutput",
    "QKPreprojectionPosition",
    "CausalControlMapper",
    "CausalEMA",
    "CausalEMAState",
    "adapt_legacy_position_state_dict",
    "apply_rotary",
    "build_attention_position_write_channel",
    "build_mapper",
    "build_qk_position_channel",
    "build_residual_position_channel",
    "build_position_basis",
    "build_rope_cache",
    "build_rope_frequencies",
    "channel_theta",
    "compose_phase",
    "count_position_parameters",
    "deep_merge",
    "ensure_channel_v2",
    "exp_with_identity_grad",
    "interleaved_fourier_basis",
    "legacy_position_run_tag",
    "legacy_rope_frequency_mode",
    "load_position_compatible_state_dict",
    "normalize_logit_bias_config",
    "normalize_position_config_v2",
    "normalize_position_content_config",
    "normalize_attention_write_config",
    "normalize_residual_stream_config",
    "normalize_rope_frequency_config",
    "normalize_rotary_clock_config",
    "normalize_position_gain_config",
    "normalize_qk_preprojection_config",
    "parameterize_rope_frequencies",
    "resolve_channel_config",
    "rotate_half",
    "upgrade_legacy_position_config",
    "v2_position_run_tag",
]
